let distancia = maqueen.Ultrasonic(PingUnit.Centimeters)
maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, 60)
basic.pause(4000)
maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CCW, 60)
maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CW, 60)
basic.pause(300)
maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, 60)
basic.pause(1000)
maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CCW, 60)
maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CW, 60)
basic.pause(300)
maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, 60)
basic.pause(1000)
maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CW, 60)
maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CCW, 60)
basic.pause(300)
maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, 60)
basic.pause(3000)
maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CCW, 60)
maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CW, 60)
basic.pause(300)
maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, 60)
basic.pause(3000)
maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CCW, 60)
maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CW, 60)
basic.pause(300)
maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, 60)
basic.pause(4000)
if (distancia < 7) {
    basic.pause(1000)
    basic.showIcon(IconNames.Confused)
    basic.pause(2000)
    soundExpression.mysterious.play()
    basic.pause(2000)
}
basic.forever(function () {
	
})
